# Generated by Django 5.0.3 on 2024-07-03 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('thumbnail', models.URLField()),
                ('is_show', models.BooleanField()),
                ('image_url', models.URLField()),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField()),
            ],
            options={
                'db_table': 'categories',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('description', models.TextField()),
                ('thumbnail', models.URLField()),
                ('url', models.URLField()),
                ('keyword', models.CharField(max_length=255)),
                ('is_permaban', models.BooleanField()),
                ('ban_expired_at', models.DateField(null=True)),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField()),
                ('count_view', models.IntegerField()),
                ('level', models.CharField(max_length=255)),
                ('duration', models.CharField(max_length=255)),
                ('tittle', models.CharField(max_length=255)),
                ('duration_time', models.DurationField()),
            ],
            options={
                'db_table': 'videos',
                'managed': False,
            },
        ),
    ]
